ALTER TABLE "Branch"
ADD COLUMN "email" VARCHAR(150),
ADD COLUMN "workingHours" VARCHAR(250),
ADD COLUMN "latitude" DOUBLE PRECISION,
ADD COLUMN "longitude" DOUBLE PRECISION,
ADD COLUMN "bannerImage" VARCHAR(255);
